/*
 * SDIO host on SDMMC2 for the CYW4343W WiFi chip (Nicla Vision)
 *
 * Register sequences follow MicroPython's ports/stm32/sdio.c
 * (MIT, Copyright (c) 2018-2019 Damien P. George), which runs this board.
 *
 * Differences: the data FIFO is polled by the CPU instead of using DMA or
 * per-word interrupts. Hardware flow control (HWFC_EN) stops the bus clock
 * whenever the FIFO is full/empty, so a slow or interrupted CPU never loses
 * data, and there is no D-cache coherency to manage for the driver's buffers.
 * The chip signals pending work on WL_HOST_WAKE (see cyw43_port.c), so no
 * SDMMC interrupt is used at all.
 *
 * Pins, kernel clock (PLL1Q) and peripheral clock come from the .ioc
 * (SDMMC2 in "SD 4 bits Wide bus" mode: CK PD6, CMD PD7, D0 PB14, D1 PB15,
 * D2 PG11, D3 PB4). Only the generated HAL_SD_MspInit() is used: the
 * generated MX_SDMMC2_SD_Init() is not called, because it would try to talk
 * to an SD card.
 */
#include "sdio.h"
#include <string.h>
#include "main.h"

extern SD_HandleTypeDef hsd2;

#define SDMMC                 SDMMC2

/* Bus clock after initialisation. The CYW4343W supports up to 50 MHz. */
#define SDIO_BUS_HZ           24000000U
#define SDIO_INIT_HZ          400000U

#define CMD_TIMEOUT_MS        1000U
#define DATA_TIMEOUT_MS       200U

#define STA_CMD_ERRORS        (SDMMC_STA_CCRCFAIL | SDMMC_STA_CTIMEOUT)
#define STA_DATA_ERRORS       (SDMMC_STA_DCRCFAIL | SDMMC_STA_DTIMEOUT | \
                               SDMMC_STA_TXUNDERR | SDMMC_STA_RXOVERR)

#define ICR_ALL               (SDMMC_ICR_CCRCFAILC | SDMMC_ICR_DCRCFAILC | SDMMC_ICR_CTIMEOUTC | \
                               SDMMC_ICR_DTIMEOUTC | SDMMC_ICR_TXUNDERRC | SDMMC_ICR_RXOVERRC | \
                               SDMMC_ICR_CMDRENDC | SDMMC_ICR_CMDSENTC | SDMMC_ICR_DATAENDC | \
                               SDMMC_ICR_DHOLDC | SDMMC_ICR_DBCKENDC | SDMMC_ICR_DABORTC | \
                               SDMMC_ICR_BUSYD0ENDC | SDMMC_ICR_SDIOITC | SDMMC_ICR_ACKFAILC | \
                               SDMMC_ICR_ACKTIMEOUTC | SDMMC_ICR_VSWENDC | SDMMC_ICR_CKSTOPC | \
                               SDMMC_ICR_IDMATEC | SDMMC_ICR_IDMABTCC)

#define ERR_TIMEOUT           (-110)
#define ERR_IO                (-5)
#define ERR_INVAL             (-22)

static void delay_us(uint32_t us)
{
  /* Only used for a few short waits around clock changes */
  volatile uint32_t n = us * (SystemCoreClock / 4000000U);
  while (n--)
  {
  }
}

/* CLKCR divider for at most `hz`: SDMMC_CK = ker_ck / (2 * div), div 0 = ker_ck */
static uint32_t clk_div(uint32_t hz)
{
  uint32_t ker = HAL_RCCEx_GetPeriphCLKFreq(RCC_PERIPHCLK_SDMMC);
  if (ker <= hz)
  {
    return 0;
  }
  return (ker + (2U * hz) - 1U) / (2U * hz);
}

void sdio_init(void)
{
  /* Generated by CubeMX from the .ioc: kernel clock source, SDMMC2 clock, pins */
  hsd2.Instance = SDMMC2;
  HAL_SD_MspInit(&hsd2);

  __HAL_RCC_SDMMC2_FORCE_RESET();
  __HAL_RCC_SDMMC2_RELEASE_RESET();

  SDMMC->CLKCR = SDMMC_CLKCR_HWFC_EN | SDMMC_CLKCR_PWRSAV | clk_div(SDIO_INIT_HZ);  // 1-bit, 400 kHz
  delay_us(10);
  SDMMC->POWER = 3;                   // card is clocked
  delay_us(10);
  SDMMC->DCTRL = SDMMC_DCTRL_RWMOD;   // read wait via SDIO_CK
  delay_us(10);
  SDMMC->MASK = 0;
}

void sdio_deinit(void)
{
  __HAL_RCC_SDMMC2_CLK_DISABLE();
}

void sdio_reenable(void)
{
  if (__HAL_RCC_SDMMC2_IS_CLK_DISABLED())
  {
    __HAL_RCC_SDMMC2_CLK_ENABLE();
    sdio_enable_high_speed_4bit();
  }
}

void sdio_enable_high_speed_4bit(void)
{
  SDMMC->POWER = 0;
  delay_us(10);
  SDMMC->CLKCR = SDMMC_CLKCR_HWFC_EN | SDMMC_CLKCR_WIDBUS_0 | clk_div(SDIO_BUS_HZ);  // 4-bit
  delay_us(10);
  SDMMC->POWER = 3;
  delay_us(10);
  SDMMC->DCTRL = SDMMC_DCTRL_SDIOEN | SDMMC_DCTRL_RWMOD;
  SDMMC->MASK = 0;
  delay_us(10);
}

/* Wait for the command response; returns the STA bits that ended the wait */
static int wait_cmd(uint32_t *sta_out)
{
  uint32_t start = HAL_GetTick();
  uint32_t sta;

  while (!((sta = SDMMC->STA) & (SDMMC_STA_CMDREND | STA_CMD_ERRORS)))
  {
    if ((HAL_GetTick() - start) > CMD_TIMEOUT_MS)
    {
      return ERR_TIMEOUT;
    }
  }
  *sta_out = sta;
  return 0;
}

int sdio_transfer(uint32_t cmd, uint32_t arg, uint32_t *resp)
{
  uint32_t sta = 0;

  SDMMC->ICR = ICR_ALL;
  SDMMC->ARG = arg;
  SDMMC->CMD = cmd | SDMMC_CMD_WAITRESP_0 | SDMMC_CMD_CPSMEN;

  int ret = wait_cmd(&sta);
  SDMMC->ICR = ICR_ALL;
  if (ret != 0)
  {
    return ret;
  }

  if ((sta & SDMMC_STA_CCRCFAIL) && (cmd == 5))
  {
    /* Errata: a CRC error is wrongly flagged for the CMD5 (R4) response */
    if (resp != NULL)
    {
      *resp = SDMMC->RESP1;
    }
    return 0;
  }
  if (sta & STA_CMD_ERRORS)
  {
    return -(0x1000000 | (int)(sta & STA_CMD_ERRORS));
  }
  if (SDMMC->RESPCMD != cmd)
  {
    return ERR_IO;
  }
  if (resp != NULL)
  {
    *resp = SDMMC->RESP1;
  }
  return 0;
}

int sdio_transfer_cmd53(uint32_t block_size, uint32_t arg, size_t len, uint8_t *buf)
{
  const bool write = ((arg >> 31) & 1U) != 0U;
  const bool block_mode = ((arg >> 27) & 1U) != 0U;
  uint32_t mode_bits;
  uint32_t dlen;

  if (block_mode)
  {
    /* Block mode: whole blocks of block_size bytes */
    uint32_t log2 = 0;
    while (((1UL << log2) < block_size) && (log2 < 14U))
    {
      log2++;
    }
    if ((1UL << log2) != block_size)
    {
      return ERR_INVAL;
    }
    mode_bits = log2 << SDMMC_DCTRL_DBLOCKSIZE_Pos;                 // DTMODE = block
    dlen = (len + block_size - 1U) & ~(block_size - 1U);
  }
  else
  {
    /* Byte mode (<= 512 bytes): SDIO multibyte transfer, as ST's HAL SDIO driver does */
    if ((len == 0U) || (len > 512U))
    {
      return ERR_INVAL;
    }
    mode_bits = SDMMC_DCTRL_DTMODE_0;                                // DBLOCKSIZE = 1 byte
    dlen = (len + 3U) & ~3U;
  }

  const uint32_t dctrl = SDMMC_DCTRL_SDIOEN | SDMMC_DCTRL_RWMOD | mode_bits
                         | ((write ? 0U : 1U) << SDMMC_DCTRL_DTDIR_Pos)
                         | SDMMC_DCTRL_DTEN;

  SDMMC->ICR = ICR_ALL;
  SDMMC->MASK = 0;
  SDMMC->IDMACTRL = 0;               // CPU moves the data
  SDMMC->DTIMER = 0x2000000;         // card data timeout, in bus clocks
  SDMMC->DLEN = dlen;

  /* For reads the data path must be armed before the command goes out */
  if (!write)
  {
    SDMMC->DCTRL = dctrl;
  }

  SDMMC->ARG = arg;
  SDMMC->CMD = 53 | SDMMC_CMD_WAITRESP_0 | SDMMC_CMD_CPSMEN;

  uint32_t sta = 0;
  int ret = wait_cmd(&sta);
  if (ret == 0)
  {
    if (sta & STA_CMD_ERRORS)
    {
      ret = -(0x1000000 | (int)(sta & STA_CMD_ERRORS));
    }
    else if (SDMMC->RESP1 & 0x800)   // R5 response: ERROR flag
    {
      ret = ERR_IO;
    }
  }
  if (ret != 0)
  {
    SDMMC->DCTRL = SDMMC_DCTRL_SDIOEN | SDMMC_DCTRL_RWMOD;
    SDMMC->ICR = ICR_ALL;
    return ret;
  }

  if (write)
  {
    SDMMC->DCTRL = dctrl;
  }

  /* Data phase: move dlen bytes through the FIFO; bytes past len are padding */
  uint32_t count = 0;
  uint32_t start = HAL_GetTick();

  while (count < dlen)
  {
    sta = SDMMC->STA;
    if (sta & STA_DATA_ERRORS)
    {
      ret = -(0x1000000 | (int)(sta & STA_DATA_ERRORS));
      break;
    }

    if (write)
    {
      if (!(sta & SDMMC_STA_TXFIFOF))
      {
        uint32_t w = 0;
        if (count < len)
        {
          size_t n = ((len - count) >= 4U) ? 4U : (len - count);
          memcpy(&w, buf + count, n);
        }
        SDMMC->FIFO = w;
        count += 4U;
        continue;
      }
    }
    else
    {
      if (!(sta & SDMMC_STA_RXFIFOE))
      {
        uint32_t w = SDMMC->FIFO;
        if (count < len)
        {
          size_t n = ((len - count) >= 4U) ? 4U : (len - count);
          memcpy(buf + count, &w, n);
        }
        count += 4U;
        continue;
      }
    }

    if ((HAL_GetTick() - start) > DATA_TIMEOUT_MS)
    {
      ret = ERR_TIMEOUT;
      break;
    }
  }

  /* Wait for the data path to finish (CRC token / end of block) */
  while ((ret == 0) && !((sta = SDMMC->STA) & (SDMMC_STA_DATAEND | STA_DATA_ERRORS)))
  {
    if ((HAL_GetTick() - start) > DATA_TIMEOUT_MS)
    {
      ret = ERR_TIMEOUT;
    }
  }
  if ((ret == 0) && (sta & STA_DATA_ERRORS))
  {
    ret = -(0x1000000 | (int)(sta & STA_DATA_ERRORS));
  }

  SDMMC->DCTRL = SDMMC_DCTRL_SDIOEN | SDMMC_DCTRL_RWMOD;
  SDMMC->ICR = ICR_ALL;
  return ret;
}
